# Generated by Django 3.1.7 on 2021-03-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='orderitems',
        ),
    ]
